name: Moving_Building
version: Umm...
api-version: 1.20
main: taewookim.MovingBuilding

commands:
  createbuild:
    permission: movingbuilding.admin

permissions:
  movingbuilding.admin:
    default: op